#print('Crie um programa que leia o comprimento do cateto oposto e do cateto adjacente de um triângulo retângulo, calcule e mostre o comprimento da hipotenusa.\n')
catetoOposto = int(input('Digite o cateto oposto do trangulo retangulo: '))
catetoAdjacente = int(input('Digite o cateto adjacente do trangulo retangulo: '))
hipotenusa = ((catetoOposto**2)+(catetoAdjacente**2))**(1/2)
print('A hipotenusa é {:.2f}'.format(hipotenusa))