nome=input('Digite o seu nome: ')
print('[Sintaxe do Python2] Usando a vírgula:')
print('É um prazer te conhecer,',nome+'!')
# print('[Sintaxe do Python2] Usando o símbolo de percentual:')
# print('É um prazer te con//hecer, %s!', nome)
print('[Sintaxe do Python3] Usando o .format :')
print('É um prazer te conhecer, {}!'.format(nome))
