entradaDoTeclado=input('Digite algo: ')
print('O tipo primitivo do conteúdo informado é: {}'.format(type(entradaDoTeclado)))
print('O conteúdo é um composto de letras e/ou números? Resposta: {}'.format(entradaDoTeclado.isalnum()))
print('O conteúdo é composto só de letras? Resposta: {}'.format(entradaDoTeclado.isalpha()))
print('O conteúdo é um número inteiro? Resposta: {}'.format(entradaDoTeclado.isdecimal()))
print('O conteúdo é um número? Resposta: {}'.format(entradaDoTeclado.isdigit()))
print('O conteúdo é um identificador (Palavra Reservada do Python? Resposta: {}'.format(entradaDoTeclado.isidentifier()))
print('O conteúdo é composto apenas por letras minúsculas? Resposta: {}'.format(entradaDoTeclado.islower()))
print('O conteúdo é um número? Resposta: {}'.format(entradaDoTeclado.isnumeric()))
print('O conteúdo é um caractere imprimível? Resposta: {}'.format(entradaDoTeclado.isprintable()))
print('O conteúdo é composto apenas por espaços? Resposta: {}'.format(entradaDoTeclado.isspace()))
print('O conteúdo é um texto com as primeiras letras capitalizadas? Resposta: {}'.format(entradaDoTeclado.istitle()))
print('O conteúdo é composto apenas por letras maiúsculas? Resposta: {}'.format(entradaDoTeclado.isupper()))
