print('Ler um número inteiro qualquer e mostre na tela a sua tabuada.')
numero = int(input('Digite um número inteiro: '))
titulo = 'Taboada do Numero '+str(numero)
print('{:-^40}'.format(titulo))
print('{:<4} +  1 = {}'.format(numero,numero*1))
print('{:<4} +  2 = {}'.format(numero,numero*2))
print('{:<4} +  3 = {}'.format(numero,numero*3))
print('{:<4} +  4 = {}'.format(numero,numero*4))
print('{:<4} +  5 = {}'.format(numero,numero*5))
print('{:<4} +  6 = {}'.format(numero,numero*6))
print('{:<4} +  7 = {}'.format(numero,numero*7))
print('{:<4} +  8 = {}'.format(numero,numero*8))
print('{:<4} +  9 = {}'.format(numero,numero*9))
print('{:<4} + 10 = {}'.format(numero,numero*10))
print('-'*40)