# Programa ler algo do teclado e informar tuudo sobre o lido
lido=input("Digite algo: ")
print('\n O conteudo de {} é do tipo: {}'.format(lido,type(lido)))
print('O conteudo digitado é letras e ou número: {} '.format(lido.isalnum()))
print('O conteudo digitado é letras: {} '.format(lido.isalpha()))
print('O conteudo digitado é ascii: {} '.format(lido.isascii()))
print('O conteudo digitado é Inteiro: {} '.format(lido.isdecimal()))
print('O conteudo digitado é digito: {} '.format(lido.isdigit()))
print('O conteudo digitado é Variável: {} '.format(lido.isidentifier()))
print('O conteudo digitado é minusculo: {} '.format(lido.islower()))
print('O conteudo digitado é número: {} '.format(lido.isnumeric()))
print('O conteudo digitado é imprimivel: {} '.format(lido.isprintable()))
print('O conteudo digitado é espaço: {} '.format(lido.isspace()))
print('O conteudo digitado é titulo: {} '.format(lido.istitle()))
print('O conteudo digitado é maiusculo: {} '.format(lido.isupper()))
